<?php
/**
 * Implements hook_services_resources
 */

function timian_service_services_resources()
{

    return [
        'dupa' => [
            'create' => [
                'help'                    => 'Test point',
                'access callback'         => '_timian_service_data_access',
                // 'access arguments' => array('view'),
                'callback'                => '_timian_service_fetch_data',
                'file'                    => [
                    'type'   => 'inc',
                    'module' => 'timian_service',
                    'name'   => 'resources/test'
                ],
                array(
                    'name' => 'ccokolwiek',
                    'type' => 'string',
                    'description' => 'A valid username',
                    'source' => array('data' => 'cokolwiek'),
                    'optional' => FALSE,
                  ),
            ]
        ]
    ];
}