<?php
/**
 * Implements hook_services_resources
 */

function timian_service_services_resources()
{

    return [
        'dupa' => [
                    'actions' => array(
                        'chuj' => array(
                          'help' => 'Login a user for a new session',
                          'callback' => '_timian_service_fetch_data',
                          'args' => array(
                            array(
                              'name' => 'mama',
                              'type' => 'string',
                              'description' => 'A valid username',
                              'source' => array('data' => 'mama'),
                              'optional' => FALSE,
                            ),
                            array(
                              'name' => 'tata',
                              'type' => 'string',
                              'description' => 'A valid password',
                              'source' => array('data' => 'tata'),
                              'optional' => FALSE,
                            ),
                          ),
                          'access callback' => '_timian_service_data_access',
                          'file'                    => [
                            'type'   => 'inc',
                            'module' => 'timian_service',
                            'name'   => 'resources/test'
                        ],
                        ),
                    )
    ]
];
}